version: '2'
services:
    shivanicorrugation-app:
        image: shivanicorrugation
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://shivanicorrugation-postgresql:5432/shivaniCorrugation
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=shivanicorrugation-elasticsearch:9300
        ports:
            - 8080:8080
    shivanicorrugation-postgresql:
        extends:
            file: postgresql.yml
            service: shivanicorrugation-postgresql
    shivanicorrugation-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: shivanicorrugation-elasticsearch
